name: main
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/main.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: x64
            host: x86_64-pc-linux-gnu
            gmp_so: libgmp.so.10.5.0
            gmp_cpp_so: libgmpxx.so.4.7.0
            strip: strip
          - os: linux
            arch: x86
            host: i686-pc-linux-gnu
            gmp_so: libgmp.so.10.5.0
            gmp_cpp_so: libgmpxx.so.4.7.0
            strip: strip
          - os: linux
            arch: arm64
            host: aarch64-linux-gnu
            gmp_so: libgmp.so.10.5.0
            gmp_cpp_so: libgmpxx.so.4.7.0
            strip: aarch64-linux-gnu-strip
          - os: linux
            arch: arm
            host: arm-linux-gnueabihf
            gmp_so: libgmp.so.10.5.0
            gmp_cpp_so: libgmpxx.so.4.7.0
            strip: arm-linux-gnueabihf-strip
          - os: win
            arch: x64
            host: x86_64-w64-mingw32
            gmp_so: libgmp-10.dll
            gmp_cpp_so: libgmpxx-4.dll
            strip: x86_64-w64-mingw32-strip
          - os: win
            arch: x86
            host: i686-w64-mingw32
            gmp_so: libgmp-10.dll
            gmp_cpp_so: libgmpxx-4.dll
            strip: i686-w64-mingw32-strip
    env:
      GMP_VERSION: 6.3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Toolchain (arch-specific)
        run: |
          sudo apt-get update
          TARGET="${{ matrix.os }}-${{ matrix.arch }}"
          case "$TARGET" in
            "linux-x86")
              sudo apt-get install -y gcc-multilib g++-multilib
              ;;
            "linux-arm64")
              sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
              sudo apt-get install -y qemu-user
              ;;
            "linux-arm")
              sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
              sudo apt-get install -y qemu-user
              ;;
            "win-x86")
              sudo apt-get install -y mingw-w64
              sudo dpkg --add-architecture i386
              sudo apt-get update
              sudo apt-get install wine32:i386
              ;;
            "win-x64")
              sudo apt-get install -y mingw-w64
              sudo apt-get install -y wine
              ;;
            "linux-x64")
              # 如果有额外需要，可在此处安装
              ;;
            *)
              echo "Error: Unsupported OS-Architecture combination: $TARGET"
              exit 1
              ;;
          esac

      - name: Download GMP Source
        run: |
          git clone --depth 1 https://github.com/gmp-mirror/gmp-${GMP_VERSION}.git

      - name: Autoreconf
        run: |
          cd gmp-${GMP_VERSION}
          autoreconf -ivf

      - name: Configure GMP
        run: |
          CONFIGURE_OPTIONS="--enable-shared --disable-static --enable-fat --enable-cxx"
          cd gmp-${GMP_VERSION}
          ./configure --host=${{ matrix.host }} ${CONFIGURE_OPTIONS}

      - name: Build GMP
        run: |
          cd gmp-${GMP_VERSION}
          make MAKEINFO=true

      - name: Check .libs
        run: |
          cd gmp-${GMP_VERSION}/.libs
          ls -l
          file ${{ matrix.gmp_so }}

      - name: Strip GMP Library
        run: |
          cd gmp-${GMP_VERSION}/.libs
          ${{ matrix.strip }} --strip-unneeded ${{ matrix.gmp_so }}
          ${{ matrix.strip }} --strip-unneeded ${{ matrix.gmp_cpp_so }}

      - name: Compile C Program
        run: |
          COMPILE_OPTIONS=".github/workflows/factorial_gmp.c -I${{ github.workspace }}/gmp-${GMP_VERSION} -L${{ github.workspace }}/gmp-${GMP_VERSION}/.libs -lgmp"
          TARGET="${{ matrix.os }}-${{ matrix.arch }}"
          case "$TARGET" in
            "linux-x86")
              gcc -m32 -o factorial_gmp $COMPILE_OPTIONS
              ;;
            "linux-arm64")
              aarch64-linux-gnu-gcc -o factorial_gmp $COMPILE_OPTIONS
              ;;
            "linux-arm")
              arm-linux-gnueabihf-gcc -o factorial_gmp $COMPILE_OPTIONS
              ;;
            "win-x86")
              i686-w64-mingw32-gcc -o factorial_gmp.exe $COMPILE_OPTIONS
              ;;
            "win-x64")
              x86_64-w64-mingw32-gcc -o factorial_gmp.exe $COMPILE_OPTIONS
              ;;
            "linux-x64")
              gcc -o factorial_gmp $COMPILE_OPTIONS
              ;;
            *)
              echo "Error: Unsupported OS-Architecture combination: $TARGET"
              exit 1
              ;;
          esac

      - name: Run C Program
        run: |
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            LD_LIBRARY_PATH=${{ github.workspace }}/gmp-${GMP_VERSION}/.libs qemu-aarch64 -L /usr/aarch64-linux-gnu/ ${GITHUB_WORKSPACE}/factorial_gmp
          elif [ "${{ matrix.arch }}" = "arm" ]; then
            LD_LIBRARY_PATH=${{ github.workspace }}/gmp-${GMP_VERSION}/.libs qemu-arm -L /usr/arm-linux-gnueabihf/ ${GITHUB_WORKSPACE}/factorial_gmp
          elif [ "${{ matrix.os }}" = "win" ]; then
            cp ${{ github.workspace }}/gmp-${GMP_VERSION}/.libs/${{ matrix.gmp_so }} .
            wine ${GITHUB_WORKSPACE}/factorial_gmp.exe
          else
            LD_LIBRARY_PATH=${{ github.workspace }}/gmp-${GMP_VERSION}/.libs ./factorial_gmp
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/gmp-${{ env.GMP_VERSION }}/gmp.h
            ${{ github.workspace }}/gmp-${{ env.GMP_VERSION }}/gmpxx.h
            ${{ github.workspace }}/gmp-${{ env.GMP_VERSION }}/.libs/${{ matrix.gmp_so }}
            ${{ github.workspace }}/gmp-${{ env.GMP_VERSION }}/.libs/${{ matrix.gmp_cpp_so }}