name: main
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.linq'
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    env:
      GMP_VERSION: 6.3
      GMP_SO_VERSION: 10.3.0
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install texinfo

      - name: Download Source
        run: |
          git clone --depth 1 https://github.com/gmp-mirror/gmp-${GMP_VERSION}.git
      - name: autoreconf
        run: |
          cd gmp-${GMP_VERSION}
          autoreconf -ivf
      - name: Configure
        run: |
          cd gmp-${GMP_VERSION}
          ./configure --enable-shared --disable-static --enable-fat --disable-doc
      - name: Build
        run: |
          cd gmp-${GMP_VERSION}
          make
      - name: Check .libs
        run: |
          cd ./gmp-${GMP_VERSION}/.libs
          ls
          file libgmp.so.${GMP_SO_VERSION}
          objdump -x libgmp.so.${GMP_SO_VERSION}
