name: main
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.linq'
  workflow_dispatch:
  

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Download GMP Source
        run: |
          git clone --depth 1 https://github.com/gmp-mirror/gmp-6.3.git
      - name: Configure GMP
        run: |
          cd gmp-6.3
          autoreconf -ivf
          ./configure --enable-shared --disable-static --enable-fat
      - name: Build GMP
        run: |
          make
      - name: Check .libs
        run: |
          cd .libs
          file libgmp.so.10.3.0
          objdump -x libgmp.so.10.3.0