name: main
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.linq'
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    env:
      GMP_VERSION: 6.3
      GMP_SO_VERSION: 10.5.0
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y m4 autoconf libtool

      - name: Download GMP Source
        run: |
          git clone --depth 1 https://github.com/gmp-mirror/gmp-${GMP_VERSION}.git

      - name: Autoreconf
        run: |
          cd gmp-${GMP_VERSION}
          autoreconf -ivf

      - name: Configure GMP
        run: |
          cd gmp-${GMP_VERSION}
          ./configure --enable-shared --disable-static --enable-fat

      - name: Build GMP
        run: |
          cd gmp-${GMP_VERSION}
          make MAKEINFO=true

      - name: Check .libs
        run: |
          cd ./gmp-${GMP_VERSION}/.libs
          ls -l
          file libgmp.so.${GMP_SO_VERSION}

      - name: Compile C Program
        run: |
          echo '#include <stdio.h>
          #include <gmp.h>
          #include <time.h>

          void calculate_factorial(unsigned long n, mpz_t result) {
              mpz_set_ui(result, 1);
              for (unsigned long i = 1; i <= n; ++i) {
                  mpz_mul_ui(result, result, i);
              }
          }

          int main() {
              unsigned long n = 100000;
              mpz_t result;
              mpz_init(result);

              clock_t start, end;
              double cpu_time_used;

              start = clock();
              calculate_factorial(n, result);
              end = clock();

              cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;

              printf("Time taken to calculate %lu! is %f seconds.\\n", n, cpu_time_used);

              mpz_clear(result);
              return 0;
          }' > factorial_gmp.c
          gcc -o factorial_gmp factorial_gmp.c -L${{ github.workspace }}/gmp-${GMP_VERSION}/.libs -lgmp

      - name: Run C Program
        run: |
          LD_LIBRARY_PATH=${{ github.workspace }}/gmp-${GMP_VERSION}/.libs ./factorial_gmp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: ${{ github.workspace }}/gmp-${GMP_VERSION}/.libs/libgmp.so.${GMP_SO_VERSION}