name: MSYS2 Setup

on:
  push:
    branches:
      - win
    paths:
      - .github/workflows/msys-test.yml

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Add MSYS2 to PATH
      run: echo "C:\msys64\usr\bin" >> $GITHUB_PATH

    - name: Run a MSYS2 command
      run: |
        where make
        make --version