name: MSYS2 Setup

on:
  push:
    branches:
      - win
    paths:
      - .github/workflows/msys-test.yml

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dump MSYS2 folder(for troubleshooting)
      run: |
        tree /F C:\msys2

    - name: Add MSYS2 to PATH
      run: echo "C:\msys2\usr\bin" >> $GITHUB_PATH

    - name: Update MSYS2
      run: |
        pacman -Syu --noconfirm

    - name: Install a package with MSYS2
      run: |
        pacman -S --noconfirm make

    - name: List installed packages
      run: |
        pacman -Q

    - name: Run a MSYS2 command
      run: |
        make --version