name: MSYS2 Setup

on:
  push:
    branches:
      - win
    paths:
      - .github/workflows/msys-test.yml

jobs:
  build:
    runs-on: windows-latest

    env:
      GMP_VERSION: 6.3.0

    steps:
    - name: Download GMP Source
      run: |
        Invoke-WebRequest -Uri https://ftpmirror.gnu.org/gmp/gmp-${env:GMP_VERSION}.tar.xz -OutFile .
        & "C:\Program Files\Git\usr\bin\tar.exe" -xvf gmp-${env:GMP_VERSION}.tar.xz

    - name: Build GMP
      shell: bash
      run: |
        cd gmp-${GMP_VERSION}
        ./configure --enable-shared --disable-static --enable-fat --enable-cxx
        make