name: MSYS2 Setup

on:
  push:
    branches:
      - win
    paths:
      - .github/workflows/msys-test.yml

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - arch: x64
            msystem: MINGW64
            gcc-package: mingw-w64-x86_64-gcc
            artifact-name: win-x64-native
            host: x86_64-w64-mingw32
          - arch: x86
            msystem: MINGW32
            gcc-package: mingw-w64-i686-gcc
            artifact-name: win-x86-native
            host: i686-w64-mingw32
          - arch: arm64
            msystem: CLANGARM64
            gcc-package: mingw-w64-clang-aarch64-gcc
            artifact-name: win-arm64-native
            host: aarch64-w64-mingw32

    env:
      GMP_VERSION: 6.3.0

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: ${{ matrix.msystem }}
        install: >-
          m4
          base-devel
          ${{ matrix.gcc-package }}

    - name: Download GMP Source
      run: |
        Invoke-WebRequest -Uri https://ftpmirror.gnu.org/gmp/gmp-${env:GMP_VERSION}.tar.xz -OutFile .
        & "C:\Program Files\Git\usr\bin\tar.exe" -xf gmp-${env:GMP_VERSION}.tar.xz

    - name: Configure
      shell: msys2 {0}
      run: |
        cd gmp-${GMP_VERSION}
        export CC=${{ matrix.host }}-gcc
        export CXX=${{ matrix.host }}-g++
        ./configure --host=${{ matrix.host }} --enable-shared --disable-static --enable-cxx --disable-fat

    - name: Make
      shell: msys2 {0}
      run: |
        cd gmp-${GMP_VERSION}
        make

    - name: Check libs
      shell: bash
      run: |
        ls -l gmp-${GMP_VERSION}/.libs

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: |
          gmp-${{ env.GMP_VERSION }}/.libs/libgmp-10.dll
          gmp-${{ env.GMP_VERSION }}/.libs/libgmpxx-4.dll
          gmp-${{ env.GMP_VERSION }}/gmp.h
          gmp-${{ env.GMP_VERSION }}/gmpxx.h